# Generated by Django 4.2.2 on 2023-07-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='english',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='social',
            field=models.IntegerField(default=0),
        ),
    ]
